import { useEffect, useState } from "react";
import { Beaker, FlaskConical, Info } from "lucide-react";
import { api } from "../api/client";
import type { EvaluationRow } from "../types";
import { Badge, Card, EmptyState, Spinner } from "../components/ui";

export function EvaluationPage() {
  const [rows, setRows] = useState<EvaluationRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    (async () => {
      try {
        setRows(await api.evaluationCompare());
      } catch (e) {
        setError((e as Error).message);
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  if (loading) return <Spinner label="Loading evaluation metrics…" />;
  if (error) return <EmptyState title="Evaluation unavailable" body={error} />;

  const cols: { key: keyof EvaluationRow; label: string }[] = [
    { key: "precision", label: "Precision" },
    { key: "recall", label: "Recall" },
    { key: "f1", label: "F1" },
    { key: "iou", label: "IoU" },
    { key: "dice", label: "Dice" },
    { key: "accuracy", label: "Accuracy" },
    { key: "false_positive_rate", label: "FP Rate" },
    { key: "false_negative_rate", label: "FN Rate" },
  ];

  function cell(row: EvaluationRow, key: keyof EvaluationRow): string {
    const v = row[key] as number | null;
    if (!row.evaluated || v === null || v === undefined) return "Not evaluated";
    return (v * 100).toFixed(1) + "%";
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-semibold text-white">Model Evaluation & Experiment Comparison</h1>
        <p className="text-sm text-slate-400">
          Honest metrics computed against synthetic ground truth. Models without trained results
          are marked "Not evaluated".
        </p>
      </div>

      <Card title="Pixel-level Metrics" subtitle="Prediction vs ground-truth change mask">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm">
            <thead>
              <tr className="border-b border-base-800 text-xs uppercase tracking-wide text-slate-400">
                <th className="py-2 pr-4">Method</th>
                {cols.map((c) => (
                  <th key={c.key} className="py-2 pr-4">{c.label}</th>
                ))}
                <th className="py-2 pr-4">Status</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((r) => (
                <tr key={r.method} className="border-b border-base-800/40 hover:bg-base-800/30">
                  <td className="py-2 pr-4 font-medium text-slate-100">{r.method}</td>
                  {cols.map((c) => (
                    <td key={c.key} className={`py-2 pr-4 ${r.evaluated ? "text-slate-300" : "text-slate-600"}`}>
                      {cell(r, c.key)}
                    </td>
                  ))}
                  <td className="py-2 pr-4">
                    {r.evaluated ? (
                      <Badge tone="green">Evaluated</Badge>
                    ) : (
                      <Badge tone="slate">Not evaluated</Badge>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>

      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        <Card title="How metrics are computed">
          <div className="space-y-2 text-sm text-slate-300">
            <p className="flex items-center gap-2"><FlaskConical className="h-4 w-4 text-accent" /> The classical baseline is evaluated on a synthetic ground-truth pair generated by the demo module.</p>
            <p className="flex items-center gap-2"><Beaker className="h-4 w-4 text-accent" /> IoU and Dice measure spatial overlap of predicted and true change masks.</p>
            <p className="flex items-center gap-2"><Info className="h-4 w-4 text-accent" /> Deep-learning methods (Siamese, U-Net, ChangeFormer, BIT) require training and are listed as "Not evaluated" until results exist.</p>
          </div>
        </Card>
        <Card title="Supported research datasets">
          <ul className="space-y-1 text-sm text-slate-300">
            <li>• LEVIR-CD — building change detection</li>
            <li>• xBD — building damage assessment</li>
            <li>• DOTA / xView — object detection</li>
            <li>• SpaceNet — building & road extraction</li>
          </ul>
          <p className="mt-2 text-xs text-slate-500">
            Integrate annotations under <code className="text-accent-soft">data/annotations</code> and
            provide ground-truth masks to enable real evaluation. See README.
          </p>
        </Card>
      </div>
    </div>
  );
}
